### ISSUE TITLE
Menu: Open in new window fails

### ISSUE THREAD

**Issue by maikuru** [maikuru/cesium#13]
The open in new window does not function.  Even the hello world is crashing.

**Comment by adi2412** [comment]
The issue is when Cesium tries to create a worker. There is a function defined in Cesium to check if the URL is cross-origin, but it seems to return false and considers the link to be not cross origin, when infact, the browser thinks it is. Either that needs to be changed, or we need to use requireJS to load Cesium for the new window. I tried that and Cesium was working fine in the new window. I think requireJS correctly handles cross origin requests in that case.
